회원가입 기능 구현
SSAFY-TOTT/Backend pull request #18
Opened 2023-09-04 06:38 UTC by KIMSEI1124

# 개요

- #15 

## 한 일

- [X] Redis 라이브러리 추가
- [X] 사용자 회원가입 임시 저장 기능 구현 
- [X] 유저 인증 정보 1원 이체 기능 구현
- [ ] 유저 인증 기능 구현
- [ ] 예금주 실명 조회 기능 구현
- [ ] 회원가입 기능 구현

## ETC

2023-09-04 23:59 UTC, BoyCho requested changes

2023-09-04 23:59 UTC, BoyCho commented on src/main/java/com/ssafy/tott/api/shinhan/service/transfer1/ShinhanBankTransfer1API.java
> +        System.out.println(json);
버그 찾은 흔적 포착뽀짝

2023-09-04 23:59 UTC, BoyCho commented on src/main/java/com/ssafy/tott/member/dto/request/MemberSignupRequest.java
> +@Data
@Data 어노테이션 수정 부탁드려요

2023-09-04 23:59 UTC, BoyCho commented on src/main/java/com/ssafy/tott/member/service/MemberService.java
> +        String bankCode = memberVerificationCache.getBankCode().getCode();
함수 깔끔하게 수정 부탁드려용

2023-09-04 23:59 UTC, BoyCho commented on src/main/java/com/ssafy/tott/member/service/MemberVerificationService.java
> +                .build();
분리하면 가독성이 좋아질 것 같은데 혹시 분리하는 건 어떨까요?

2023-09-05 00:10 UTC, KIMSEI1124 commented on src/main/java/com/ssafy/tott/api/shinhan/service/transfer1/ShinhanBankTransfer1API.java
> +        System.out.println(json);
수정하였습니다! 2e9307b

2023-09-05 00:10 UTC, KIMSEI1124 commented on src/main/java/com/ssafy/tott/member/dto/request/MemberSignupRequest.java
> +@Data
`@Getter` 로 수정하였습니다!

- 2e9307b

2023-09-05 00:10 UTC, KIMSEI1124 commented on src/main/java/com/ssafy/tott/member/service/MemberService.java
> +        String bankCode = memberVerificationCache.getBankCode().getCode();
함수를 연속적으로 호출 하지 않게 수정하였습니다!

- 2e9307b

2023-09-05 00:11 UTC, KIMSEI1124 commented on src/main/java/com/ssafy/tott/member/service/MemberVerificationService.java
> +                .build();
해당 커밋에서 분리하였습니다!

- 4683790

2023-09-05 04:14 UTC, goldapple-ce submitted a review, later dismissed

2023-09-05 04:33 UTC, BoyCho approved these changes

2023-09-05 06:32 UTC, BoyCho approved these changes

2023-09-05 10:09 UTC, goldapple-ce approved these changes

2023-09-05 10:16 UTC, merged